services:
  db:
    image: postgres:16
    container_name: andesfin_db
    environment:
      POSTGRES_USER: andesfin_user
      POSTGRES_PASSWORD: andesfin_pass
      POSTGRES_DB: andesfin_db
    ports:
      - "5432:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
